name = "arm"
marker-team = true

[people]
leads = []
members = [
    "JamieCunliffe",
    "Stammark",
    "joaopaulocarreiro",
    "raw-bin",
    "vigoux",
    "your_name_here", # Don't forget to run `cargo run add-person` if you're new!
]
