name = "icebreakers-llvm"
marker-team = true

[people]
leads = []
members = [
    "comex",
    "hdhoang",
    "heyrutvik",
    "JOE1994",
    "jryans",
    "mmilenko",
    "nagisa",
    "nikic",
    "hanna-kruppe",
    "SiavoshZarrasvand",
    "spastorino",
    "vertexclique",
    "vgxbj",
    "Noah-Kennedy",
]
