name = "icebreakers-cleanup-crew"
marker-team = true

[people]
leads = []
members = [
    "spastorino",
    "shekohex",
    "hdhoang",
    "pierreN",
    "hellow554",
    "robjtede",
    "mental32",
    "chrissimpkins",
    "senden9",
    "pard68",
    "sinato",
    "turboladen",
    "DutchGhost",
]
