name = "wg-ffi-unwind"
subteam-of = "lang"
wg = true

[people]
leads = ["nikomatsakis", "acfoltzer", "BatmanAoD"]
members = [
    "acfoltzer",
    "Amanieu",
    "BatmanAoD",
    "gnzlbg",
    "nikomatsakis",
]

[website]
name = "ffi-unwind project group"
description = "Figureing out how unwinding and FFI should interact"
repo = "https://github.com/rust-lang/project-ffi-unwind"

[github]
orgs = ["rust-lang"]
